# Generated by Django 3.2.3 on 2021-10-14 04:50

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=122, null=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(default=True, max_length=12, null=True)),
                ('email', models.CharField(default=True, max_length=122, null=True)),
                ('desc', models.TextField(default=True, null=True, verbose_name=builtins.max)),
                ('date', models.DateField(default=True, null=True)),
            ],
        ),
    ]
