# Generated by Django 3.2.3 on 2021-10-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20211013_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=True, max_length=12),
        ),
    ]
