# Generated by Django 3.2.3 on 2021-10-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default=True, max_length=122),
        ),
    ]
